version: "4.0"
services:
  db:
    container_name: ${CONTAINER_NAME}
    image: postgres
    restart: always
    ports:
      - "1021:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_${CONTAINER_NAME}:/var/lib/postgresql/data
